services:

  mysql:
    build:
      dockerfile_inline: |
          FROM mariadb:10.6
          RUN apt-get update \
          && apt-get install --no-install-recommends -y tzdata git \
          && rm -r /var/lib/apt/lists/* \
          && apt-get clean
    container_name: mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s 
        max_attempts: 3
        window: 120s
    environment:
      MYSQL_DATABASE: pcs_all_bdd
      MYSQL_USER: serveur
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
      - mysql_password
    ports:
      - "3306:3306"
    volumes:
      #- mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #networks:
    #  projetDocker:
    #    ipv4_address: 172.23.0.2

  api:
    container_name: api
    build: 
      context: https://github.com/n8lik/PA_DOCKER_BOURDIN_TECHER_LOPES_LEFEVRE.git
      dockerfile: API/Dockerfile
      no_cache: true
    environment:
      DB_NAME: pcs_all_bdd
      DB_USER: serveur
      DB_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_password
    ports:
      - "8000:80"
    restart: on-failure:5
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - projetDocker      

  front:
    container_name: front
    image: front
    ports:
      - "80:80"
    depends_on:
      - api
    scale: 1
    networks:
      - projetDocker

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.secret
  mysql_password:
    file: ./secrets/mysql_password.secret

volumes:
  mysql_data:

networks:
  projetDocker:
    driver: bridge
    ipam:
     config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
          aux_addresses:
            mysql: 172.28.0.2